export const FETCH_BEES_REQUEST = "BEES/FETCH_BEES_REQUEST";
export const BEES_RECEIVED = "BEES/BEES_RECEIVED";
export const BEES_REQUEST_FAILED = "BEES/BEES_REQUEST_FAILED";

export const CREATE_BEE_REQUEST = "BEES/CREATE_BEE_REQUEST";
export const CREATE_BEE_SUCCESSFUL = "BEES/CREATE_BEE_SUCCESSFUL";
export const CREATE_BEE_FAILED = "BEES/CREATE_BEE_FAILED";

export const REMOVE_ALL_BEES_REQUEST = "BEES/REMOVE_ALL_BEES_REQUEST";
export const REMOVE_ALL_BEES_SUCCESSFUL = "BEES/REMOVE_ALL_BEES_SUCCESSFUL";
export const REMOVE_ALL_BEES_FAILED = "BEES/REMOVE_ALL_BEES_FAILED";

export const REMOVE_BEE_REQUEST = "BEES/REMOVE_BEE_REQUEST";
export const REMOVE_BEE_SUCCESSFUL = "BEES/REMOVE_BEE_SUCCESSFUL";
export const REMOVE_BEE_FAILED = "BEES/REMOVE_BEE_FAILED";
