export const FETCH_PAYROLL_REQUEST = "PAYROLL/FETCH_PAYROLL_REQUEST";
export const PAYROLL_RECEIVED = "PAYROLL/PAYROLL_RECEIVED";
export const PAYROLL_REQUEST_FAILED = "PAYROLL/PAYROLL_REQUEST_FAILED";
