export const FETCH_TIMESHEETS_REQUEST = "TIMESHEETS/FETCH_TIMESHEETS_REQUEST";
export const TIMESHEETS_RECEIVED = "TIMESHEETS/TIMESHEETS_RECEIVED";
export const TIMESHEETS_REQUEST_FAILED = "TIMESHEETS/TIMESHEETS_REQUEST_FAILED";

export const CREATE_TIMESHEET_REQUEST = "TIMESHEETS/CREATE_TIMESHEET_REQUEST";
export const CREATE_TIMESHEET_SUCCESSFUL =
  "TIMESHEETS/CREATE_TIMESHEET_SUCCESSFUL";
export const CREATE_TIMESHEET_FAILED = "TIMESHEETS/CREATE_TIMESHEET_FAILED";

export const DISMISS_TIMESHEET_ERROR = "TIMESHEETS/DISMISS_TIMESHEET_ERROR";
